config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'health', to: 'home#show'
  get 'audit', to: 'home#audit'

  get 'my-modules', to: 'learning#show' # @see User#course
  get 'about-training', to: 'training/modules#index', as: :course_overview

  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unprocessable_entity', via: :all
  get '/500', to: 'errors#internal_server_error', via: :all

  resources :settings, controller: :settings, only: %i[show create]

  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               confirmations: 'confirmations',
               passwords: 'passwords',
               registrations: 'registrations',
             },
             path_names: {
               sign_in: 'sign-in',
               sign_out: 'sign-out',
               sign_up: 'sign-up',
             }

  # @see TimeoutWarning js component
  # @note these path names are required
  devise_scope :user do
    get 'check_session_timeout', to: 'timeout#check'
    get 'extend_session', to: 'timeout#extend'
    get 'users/timeout', to: 'timeout#timeout_user'
  end

  namespace :registration do
    resource :name, only: %i[edit update]
    resource :setting_type, only: %i[edit update], path: 'setting-type'
    resource :setting_type_other, only: %i[edit update], path: 'setting-type-other'
    resource :local_authority, only: %i[edit update], path: 'local-authority'
    resource :role_type, only: %i[edit update], path: 'role-type'
    resource :role_type_other, only: %i[edit update], path: 'role-type-other'
    resource :training_emails, only: %i[edit update], path: 'training-emails'
    resource :early_years_emails, only: %i[edit update], path: 'early-years-emails'
  end

  resource :user, controller: :user, only: %i[show], path: 'my-account' do
    get 'edit-email'
    get 'edit-password'
    patch 'update-email'
    patch 'update-password'
    get 'check-email-confirmation'
    get 'check-email-password-reset'
    get 'edit-training-emails'
    patch 'update-training-emails'

    resource :close_account, only: %i[new update show], path: 'close' do
      get 'reset-password'
      get 'edit-reason'
      patch 'update-reason'
      get 'confirm'
      post 'close_account'
    end

    scope module: 'training' do
      resource :notes, path: 'learning-log', only: %i[show create update]
    end
  end

  constraints proc { Rails.application.preview? || Rails.env.test? } do
    resources :snippets, id: /[^\/]+/, only: %i[show]
  end

  scope module: 'training' do
    resources :modules, only: %i[show], as: :training_modules do
      resources :pages, only: %i[index show], path: 'content-pages'
      resources :questions, only: %i[show], path: 'questionnaires'
      resources :responses, only: %i[update]
      resources :assessments, only: %i[show new], path: 'assessment-result'
    end
  end

  post '/change', to: 'hook#change'
  post '/release', to: 'hook#release'

  resources :pages, only: %i[show], path: '/', as: :static
end

app/controllers/concerns/learning.rb
module Learning
  # ----------------------------------------------------------------------------
  # Request Params
  # ----------------------------------------------------------------------------

  # @return [String]
  def mod_name
    params[:training_module_id]
  end

  # @return [String]
  def content_name
    params[:id]
  end

  # ----------------------------------------------------------------------------
  # Contentful Entries
  # ----------------------------------------------------------------------------

  # @return [Training::Module]
  def mod
    Training::Module.by_name(mod_name)
  end

  # @return [Training::Page, Training::Video, Training::Question]
  def content
    mod.page_by_name(content_name)
  end

  # ----------------------------------------------------------------------------
  # Progress Services
  # ----------------------------------------------------------------------------

  # @return [AssessmentProgress]
  def assessment
    helpers.assessment_progress_service(mod)
  end

  # @return [ModuleProgress]
  def progress_service
    helpers.module_progress_service(mod)
  end

  # ----------------------------------------------------------------------------
  # Decorated Services
  # ----------------------------------------------------------------------------

  # @return [ModuleOverviewDecorator]
  def module_progress
    ModuleOverviewDecorator.new(progress_service)
  end

  # @return [ModuleProgressBarDecorator]
  def progress_bar
    ModuleProgressBarDecorator.new(progress_service)
  end

  # ----------------------------------------------------------------------------
  # Database Records
  # ----------------------------------------------------------------------------

  # @note memoization ensures validation errors work
  # @return [UserAnswer, Response]
  def current_user_response
    @current_user_response ||= current_user.response_for(content)
  end
end

app/controllers/learning_controller.rb
# frozen_string_literal: true

class LearningController < ApplicationController
  before_action :authenticate_registered_user!
  layout 'main_hero'

  # GET /my-modules
  def show
    track('learning_page')
  end
end

app/views/learning/_card.html.slim
.card
  .card-container
    = training_module_image(mod)
    h3.govuk-heading-m
      = govuk_link_to mod.card_title, training_module_path(mod.name), no_visited_state: true, class: 'card-link--header'
    - if current
      = link_to_retake_or_results(mod)

app/views/learning/_cms_debug.html.slim
- if debug?
  pre.debug_dump
    h4 Deployment
    | instance: #{ENV['CF_INSTANCE_INDEX']}
    h4 Contentful
    | env: #{ContentfulRails.configuration.environment}
    br
    | API (ContentfulModel): #{ContentfulModel.use_preview_api ? 'preview' : 'delivery'}
    br
    | API (ContentfulRails): #{ContentfulRails.configuration.enable_preview_domain ? 'preview' : 'delivery'}
    hr
    h4 Cache
    | key: #{Training::Module.cache_key}
    br
    | size: #{Training::Module.cache.size}

app/views/learning/_debug.html.slim
- if debug?
  pre.debug_dump
    - current_user.course.debug_summary.each do |summary|
      = summary
      hr

app/views/learning/show.html.slim
- content_for :page_title do
  = html_title t(:title, scope: :my_learning)

= render 'cms_debug'

- content_for :hero do 
  div class='govuk-grid-row govuk-!-padding-top-9 govuk-!-padding-bottom-0'
    .govuk-grid-column-three-quarters
      h1 class='govuk-heading-xl govuk-!-margin-bottom-4'
        | My modules
      p You can complete the Early years child development training in any order. However, to support your understanding of the training, you may find it helpful to complete the modules in order.

hr.govuk-section-break.govuk-section-break--visible.govuk-section-break--l

.govuk-grid-row id='started'
  .govuk-grid-column-full
    h2.govuk-heading-m Modules in progress
    - if current_user.course.current_modules.none?
      - if current_user.course.completed_modules.none?
        p You have not started any modules. To begin the training course, start an available module.
      - else
        p You have not started any modules. Please choose an available module.
    - else
      .grid-container
        - current_user.course.current_modules.each do |mod|
          = render 'card', mod: mod, current: true

- if current_user.course.available_modules.any? || current_user.course.course_completed?
  hr.govuk-section-break.govuk-section-break--visible.govuk-section-break--l
  .govuk-grid-row id='available'
    .govuk-grid-column-full
      h2.govuk-heading-m Available modules
      - if current_user.course.available_modules.any?
        .grid-container
          - current_user.course.available_modules.each do |mod|
            = render 'card', mod: mod, current: false

      - elsif current_user.course.course_completed?
        p You do not have any modules available.

- if current_user.course.upcoming_modules.any?
  hr.govuk-section-break.govuk-section-break--visible.govuk-section-break--l
  .govuk-grid-row id='upcoming'
    .govuk-grid-column-full
      h2.govuk-heading-m Future modules in this course

      .grid-container
        - current_user.course.upcoming_modules.each do |mod|
          .govuk-card id=mod.name
            h3.govuk-heading-s
              = mod.card_title
            p.govuk-body= mod.short_description
            - unless mod.draft?
              = govuk_link_to 'View more information about this module',
                course_overview_path + mod.card_anchor

- if current_user.course.completed_modules.any?
  hr.govuk-section-break.govuk-section-break--visible.govuk-section-break--l
  .govuk-grid-row id='completed'
    .govuk-grid-column-three-quarters-from-desktop
      = completed_modules_table

= render 'debug'