config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'health', to: 'home#show'
  get 'audit', to: 'home#audit'

  get 'my-modules', to: 'learning#show' # @see User#course
  get 'about-training', to: 'training/modules#index', as: :course_overview

  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unprocessable_entity', via: :all
  get '/500', to: 'errors#internal_server_error', via: :all

  resources :settings, controller: :settings, only: %i[show create]

  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               confirmations: 'confirmations',
               passwords: 'passwords',
               registrations: 'registrations',
             },
             path_names: {
               sign_in: 'sign-in',
               sign_out: 'sign-out',
               sign_up: 'sign-up',
             }

  # @see TimeoutWarning js component
  # @note these path names are required
  devise_scope :user do
    get 'check_session_timeout', to: 'timeout#check'
    get 'extend_session', to: 'timeout#extend'
    get 'users/timeout', to: 'timeout#timeout_user'
  end

  namespace :registration do
    resource :name, only: %i[edit update]
    resource :setting_type, only: %i[edit update], path: 'setting-type'
    resource :setting_type_other, only: %i[edit update], path: 'setting-type-other'
    resource :local_authority, only: %i[edit update], path: 'local-authority'
    resource :role_type, only: %i[edit update], path: 'role-type'
    resource :role_type_other, only: %i[edit update], path: 'role-type-other'
    resource :training_emails, only: %i[edit update], path: 'training-emails'
    resource :early_years_emails, only: %i[edit update], path: 'early-years-emails'
  end

  resource :user, controller: :user, only: %i[show], path: 'my-account' do
    get 'edit-email'
    get 'edit-password'
    patch 'update-email'
    patch 'update-password'
    get 'check-email-confirmation'
    get 'check-email-password-reset'
    get 'edit-training-emails'
    patch 'update-training-emails'

    resource :close_account, only: %i[new update show], path: 'close' do
      get 'reset-password'
      get 'edit-reason'
      patch 'update-reason'
      get 'confirm'
      post 'close_account'
    end

    scope module: 'training' do
      resource :notes, path: 'learning-log', only: %i[show create update]
    end
  end

  constraints proc { Rails.application.preview? || Rails.env.test? } do
    resources :snippets, id: /[^\/]+/, only: %i[show]
  end

  scope module: 'training' do
    resources :modules, only: %i[show], as: :training_modules do
      resources :pages, only: %i[index show], path: 'content-pages'
      resources :questions, only: %i[show], path: 'questionnaires'
      resources :responses, only: %i[update]
      resources :assessments, only: %i[show new], path: 'assessment-result'
    end
  end

  post '/change', to: 'hook#change'
  post '/release', to: 'hook#release'

  resources :pages, only: %i[show], path: '/', as: :static
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_registered_user!, only: %i[audit]

  def index
    track('home_page')
  end

  def show
    render json: { status: 'HEALTHY' }, status: :ok
  end

  def audit
    render plain: 'BOT ACCESS GRANTED', status: :ok
  end
end

app/views/home/index.html.slim
- content_for :page_title do
  = html_title t('home.title')

= render 'learning/cms_debug'

- if debug?
  pre.debug_dump
    = configuration_summary_list

.govuk-grid-row
  .govuk-grid-column-full
    .light-grey-box
      .govuk-grid-row
        .govuk-grid-column-two-thirds
          = content_resource 'home.hero', service_name: service_name

          = govuk_button_link_to course_overview_path, class: 'govuk-button--start govuk-!-margin-bottom-4' do
            - if current_user
              | Learn more
            - else
              | Learn more and enrol
              p.govuk-visually-hidden on the course

            svg.govuk-button__start-icon xmlns='http://www.w3.org/2000/svg' width='17.5' height='19' viewBox='0 0 33 40' aria-hidden='true' focusable='false'
              path fill='currentColor' d='M0 0h13l20 20-20 20H0l20-20z'

        .govuk-grid-column-one-third
          = content_resource 'home.thumb'

.govuk-grid-row
  .govuk-grid-column-one-half
    = content_resource 'home.about'

  - unless current_user
    .govuk-grid-column-one-half
      .light-grey-box
        = content_resource 'home.login'

        .govuk-button-group
          = govuk_button_link_to 'Sign in', new_user_session_path
          .white-space-pre-wrap= ' or '
          = govuk_link_to 'create an account', new_user_registration_path