config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'health', to: 'home#show'
  get 'audit', to: 'home#audit'

  get 'my-modules', to: 'learning#show' # @see User#course
  get 'about-training', to: 'training/modules#index', as: :course_overview

  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unprocessable_entity', via: :all
  get '/500', to: 'errors#internal_server_error', via: :all

  resources :settings, controller: :settings, only: %i[show create]

  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               confirmations: 'confirmations',
               passwords: 'passwords',
               registrations: 'registrations',
             },
             path_names: {
               sign_in: 'sign-in',
               sign_out: 'sign-out',
               sign_up: 'sign-up',
             }

  # @see TimeoutWarning js component
  # @note these path names are required
  devise_scope :user do
    get 'check_session_timeout', to: 'timeout#check'
    get 'extend_session', to: 'timeout#extend'
    get 'users/timeout', to: 'timeout#timeout_user'
  end

  namespace :registration do
    resource :name, only: %i[edit update]
    resource :setting_type, only: %i[edit update], path: 'setting-type'
    resource :setting_type_other, only: %i[edit update], path: 'setting-type-other'
    resource :local_authority, only: %i[edit update], path: 'local-authority'
    resource :role_type, only: %i[edit update], path: 'role-type'
    resource :role_type_other, only: %i[edit update], path: 'role-type-other'
    resource :training_emails, only: %i[edit update], path: 'training-emails'
    resource :early_years_emails, only: %i[edit update], path: 'early-years-emails'
  end

  resource :user, controller: :user, only: %i[show], path: 'my-account' do
    get 'edit-email'
    get 'edit-password'
    patch 'update-email'
    patch 'update-password'
    get 'check-email-confirmation'
    get 'check-email-password-reset'
    get 'edit-training-emails'
    patch 'update-training-emails'

    resource :close_account, only: %i[new update show], path: 'close' do
      get 'reset-password'
      get 'edit-reason'
      patch 'update-reason'
      get 'confirm'
      post 'close_account'
    end

    scope module: 'training' do
      resource :notes, path: 'learning-log', only: %i[show create update]
    end
  end

  constraints proc { Rails.application.preview? || Rails.env.test? } do
    resources :snippets, id: /[^\/]+/, only: %i[show]
  end

  scope module: 'training' do
    resources :modules, only: %i[show], as: :training_modules do
      resources :pages, only: %i[index show], path: 'content-pages'
      resources :questions, only: %i[show], path: 'questionnaires'
      resources :responses, only: %i[update]
      resources :assessments, only: %i[show new], path: 'assessment-result'
    end
  end

  post '/change', to: 'hook#change'
  post '/release', to: 'hook#release'

  resources :pages, only: %i[show], path: '/', as: :static
end

app/models/user.rb
class User < ApplicationRecord
  include ToCsv

  # @return [Array<String>] non-identifiable attributes for KPI tracking
  DASHBOARD_ATTRS = %w[
    id
    local_authority
    setting_type
    setting_type_other
    role_type
    role_type_other
    registration_complete
    private_beta_registration_complete
    registration_complete_any?
    registered_at
    terms_and_conditions_agreed_at
  ].freeze

  # @return [Array<String>]
  def self.dashboard_headers
    DASHBOARD_ATTRS + Training::Module.live.map { |mod| "module_#{mod.position}_time" }
  end

  # Include default devise modules. Others available are:
  # :timeoutable, :trackable, :recoverable and :omniauthable
  attr_accessor :context

  devise :database_authenticatable, :registerable, :recoverable,
         :validatable, :rememberable, :confirmable, :lockable, :timeoutable

  has_many :responses
  has_many :user_answers

  has_many :user_assessments
  has_many :visits, class_name: 'Ahoy::Visit'
  has_many :events, class_name: 'Ahoy::Event'
  has_many :notes

  # TODO: use scope with email alert
  # created an account within public beta but still not using service
  scope :registration_incomplete, -> { where(registration_complete: false) }

  # completed registration within public beta (may include private beta users)
  scope :registration_complete, -> { where(registration_complete: true) }

  # @note
  #   The default for :registration_complete was originally nil,
  #   when the registration journey was revised,
  #   the existing :registration_complete boolean was renamed,
  #   and the default changed to false
  #
  scope :registered_since_private_beta, -> { where(private_beta_registration_complete: false) }

  # completed registration in both private and public beta
  scope :reregistered, -> { where(private_beta_registration_complete: true, registration_complete: true) }

  # only registered to completion within private beta
  scope :private_beta_only_registration_complete, -> { where(private_beta_registration_complete: true, registration_complete: false) }

  # registered within private beta but never completed
  scope :private_beta_only_registration_incomplete, -> { where(private_beta_registration_complete: nil) }

  # new users only
  scope :public_beta_only_registration_complete, -> { registered_since_private_beta.registration_complete }

  scope :since_public_beta, -> { where(created_at: Rails.application.public_beta_launch_date..Time.zone.now) }

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  scope :unconfirmed, -> { where(confirmed_at: nil) }
  scope :locked_out, -> { where.not(locked_at: nil) }
  scope :since_public_beta, -> { where(created_at: Rails.application.public_beta_launch_date..Time.zone.now) }
  scope :month_old_confirmation, -> { where(confirmed_at: 4.weeks.ago.beginning_of_day..4.weeks.ago.end_of_day) }
  scope :with_local_authority, -> { where.not(local_authority: nil) }
  scope :with_notes, -> { joins(:notes).distinct.select(&:has_notes?) }
  scope :not_started_training, -> { reject(&:course_started?) }
  scope :course_in_progress, -> { select(&:course_in_progress?) }

  scope :pre_nudge_mail_confirmation, -> { where("confirmed_at < ?", Rails.application.nudge_email_launch_date - 4.weeks) }
  scope :training_email_recipients, -> { where(training_emails: [true, nil]) }
  scope :early_years_email_recipients, -> { where(early_years_emails: true) }
  scope :without_notes, -> { where.not(id: with_notes) }

  scope :closed, -> { where.not(closed_at: nil) }
  scope :not_closed, -> { where(closed_at: nil) }
  validates :closed_reason, presence: true, if: -> { context == :close_account }
  validates :closed_reason_custom, presence: true, if: proc { |u| u.closed_reason == 'other' }

  scope :with_assessments, -> { joins(:user_assessments) }
  scope :with_passing_assessments, -> { with_assessments.merge(UserAssessment.passes) }

  scope :start_training_mail_job_recipients, -> { order(:id).training_email_recipients.month_old_confirmation.registration_complete.not_started_training }
  scope :complete_registration_mail_job_recipients, -> { order(:id).training_email_recipients.month_old_confirmation.registration_incomplete }
  scope :continue_training_mail_job_recipients, -> { order(:id).training_email_recipients.select(&:continue_training_recipient?) }
  scope :new_module_mail_job_recipients, -> { order(:id).training_email_recipients.select(&:completed_available_modules?) }
  scope :historical_start_training_mail_job_recipients, -> { order(:id).training_email_recipients.pre_nudge_mail_confirmation.registration_complete.not_started_training }
  scope :historical_complete_registration_mail_job_recipients, -> { order(:id).training_email_recipients.pre_nudge_mail_confirmation.registration_incomplete }

  scope :dashboard, -> { not_closed }

  validates :first_name, :last_name, :setting_type_id,
            presence: true,
            if: proc { |u| u.registration_complete? }
  validates :role_type, presence: true, if: proc { |u| u.role_type_required? }
  validates :setting_type_id,
            inclusion: { in: Trainee::Setting.valid_types },
            if: proc { |u| u.registration_complete? }

  validates :terms_and_conditions_agreed_at, presence: true, allow_nil: false, on: :create

  # @return [Boolean]
  def has_notes?
    notes.any?(&:filled?)
  end

  # @see Devise database_authenticatable
  # @param params [Hash]
  # @return [Boolean]
  def update_with_password(params)
    if params[:password].blank?
      errors.add :password, :blank
      return false
    end

    super
  end

  # @see ResponsesController#response_params
  # @param content [Training::Question]
  # @return [UserAnswer, Response]
  def response_for(content)
    if ENV['DISABLE_USER_ANSWER'].present?
      responses.find_or_initialize_by(
        question_name: content.name,
        training_module: content.parent.name,
        archived: false,
      )
    else
      user_answers.find_or_initialize_by(
        assessments_type: content.assessments_type,
        module: content.parent.name,
        name: content.name,
        questionnaire_id: 0,
        question: 'N/A for CMS only questions',
        archived: nil,
      )
    end
  end

  # @return [Array<Training::Module>]
  def active_modules
    Training::Module.live.select do |mod|
      module_time_to_completion.key?(mod.name)
    end
  end

  # @see Devise::Confirmable
  # send_confirmation_instructions
  def send_confirmation_instructions
    unless @raw_confirmation_token
      generate_confirmation_token!
    end

    opts = pending_reconfirmation? ? { to: unconfirmed_email } : {}
    mailer = registration_complete? ? :email_confirmation_instructions : :activation_instructions
    send_devise_notification(mailer, @raw_confirmation_token, opts)
  end

  # send email to registered user if attempt is made to create account with registered email
  def send_email_taken_notification
    send_devise_notification(:email_taken)
  end

  def send_account_closed_notification
    send_devise_notification(:account_closed)
  end

  # TODO: refactor this internal user mailer logic
  def send_account_closed_internal_notification(user_account_email)
    send_devise_notification(:account_closed_internal, user_account_email)
  end

  def send_complete_registration_notification
    send_devise_notification(:complete_registration)
  end

  def send_start_training_notification
    send_devise_notification(:start_training)
  end

  # @param mod [Training::Module]
  def send_continue_training_notification(mod)
    send_devise_notification(:continue_training, mod)
  end

  # @param mod [Training::Module]
  def send_new_module_notification(mod)
    send_devise_notification(:new_module, mod)
  end

  # @return [String]
  def name
    [first_name, last_name].compact.join(' ')
  end

  # @return [String]
  def email_to_confirm
    pending_reconfirmation? ? unconfirmed_email : email
  end

  # @return [String]
  def password_last_changed
    timestamp = password_changed_events&.last&.time || created_at
    timestamp.to_date&.to_formatted_s(:rfc822)
  end

  # @return [CourseProgress] course activity query interface
  def course
    @course ||= CourseProgress.new(user: self)
  end

  # @return [Boolean]
  def course_started?
    !module_time_to_completion.empty?
  end

  # @return [Boolean]
  def course_in_progress?
    course_started? && !module_time_to_completion.values.all?(&:positive?)
  end

  # @return [Array<String>]
  def modules_in_progress
    module_time_to_completion.select { |_k, v| v.zero? }.keys
  end

  # @param module_name [String]
  # @return [Boolean]
  def module_completed?(module_name)
    module_time_to_completion.key?(module_name) && module_time_to_completion[module_name].positive?
  end

  # @return [Integer]
  def modules_completed
    module_time_to_completion.values.count(&:positive?)
  end

  # @return [String]
  def authority_name
    (local_authority.presence || 'Multiple')
  end

  # @return [String]
  def setting_name
    setting_other? ? setting_type_other : setting.title
  end

  # @return [String]
  def role_name
    role_other? ? role_type_other : role_type
  end

  # @return [Boolean]
  def childminder?
    setting_other? ? false : setting.role_type.eql?('childminder')
  end

  # @return [Boolean]
  def role_type_required?
    return false unless setting_type_id
    return false unless registration_complete?
    return true if setting_other?
    return false unless setting_valid?
    return true if select_new_role?
  end

  # @return [Boolean]
  def setting_valid?
    Trainee::Setting.valid_types.include?(setting_type_id)
  end

  # @return [Boolean]
  def select_new_role?
    return false unless setting_type_id_changed?

    new_value = setting_type_id_change[1]

    Trainee::Setting.by_name(new_value).has_role?
  end

  # @return [Boolean]
  def setting_local_authority?
    setting_type_id == 'local_authority'
  end

  # @return [Boolean]
  def setting_other?
    setting_type_id == 'other'

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_registered_user!,
                except: %i[check_email_confirmation check_email_password_reset]

  def show
    track('profile_page')
  end

  def edit_name; end

  def edit_password; end

  def edit_email; end

  def edit_training_emails; end

  def update_name
    if current_user.update(user_params)
      track('user_name_change', success: true)
      redirect_to user_path, notice: 'You have saved your details'
    else
      track('user_name_change', success: false)
      render :edit_name, status: :unprocessable_entity
    end
  end

  # @see config/initializers/devise.rb
  def update_password
    if current_user.update_with_password(user_password_params)
      track('user_password_change', success: true)
      bypass_sign_in(current_user)
      redirect_to user_path, notice: 'Your new password has been saved.'
    else
      track('user_password_change', success: false)
      render :edit_password, status: :unprocessable_entity
    end
  end

  def update_email
    if current_user.update(user_params)
      track('user_email_change', success: true)
      redirect_to user_path, notice: t('notice.email_changed')
    else
      track('user_email_change', success: false)
      render :edit_email, status: :unprocessable_entity
    end
  end

  def update_training_emails
    if current_user.update(user_params)
      track('user_training_emails_change', success: true)
      redirect_to user_path, notice: 'Your email preferences have been saved.'
    else
      track('user_training_emails_change', success: false)
      render :edit_training_emails, status: :unprocessable_entity
    end
  end

  def check_email_confirmation
    return unless params[:ref]

    @user = User.find_by(confirmation_token: params[:ref])
  end

  def check_email_password_reset; end

private

  # def user
  #   @user ||= current_user
  # end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :postcode, :ofsted_number, :email, :setting_type, :setting_type_other, :training_emails)
  end

  def user_password_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end
end

app/controllers/users/notes_controller.rb
class Users::NotesController < ApplicationController
  before_action :authenticate_registered_user!
  helper_method :note

  def show
    @training_modules = TrainingModule.where(draft: nil)
  end

  def create
    note = User::Note.new(note_params)
    @model = module_item.model

    if note.save
      track('user_notes', **tracking_properties)
      redirect_to training_module_content_page_path(module_item.training_module, module_item.next_item)
    else
      render "content_pages/#{module_item.type}", local: { note: note }
    end
  end

  def update
    note = User::Note.find permitted_params[:id]
    @model = module_item.model

    if note.update(note_params)
      track('user_notes', **tracking_properties)
      redirect_to training_module_content_page_path(module_item.training_module, module_item.next_item)
    else
      render "content_pages/#{module_item.type}", local: { note: note }
    end
  end

private

  def existing_note
    current_user.notes.where(training_module: training_module_name, name: note_name).first
  end

  def new_note
    User::Note.new
  end

  def note
    @note ||= existing_note || new_note
  end

  def tracking_properties
    module_item.attributes.merge(note_id: note.id)
  end

  def module_item
    @module_item ||= ModuleItem.find_by(id: permitted_params[:module_item_id])
  end

  def note_params
    permitted_params.permit(:title, :body, :training_module, :name).with_defaults(user: current_user)
  end

  def training_module_name
    permitted_params[:training_module]
  end

  def note_name
    permitted_params[:name]
  end

  def permitted_params
    params.require(:user_note).permit(:id, :module_item_id, :title, :body, :training_module, :name)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
protected

  def after_sign_in_path_for(resource)
    if resource.registration_complete?
      if resource.display_whats_new?
        resource.display_whats_new = false
        resource.save!
        static_path('whats-new')
      elsif !resource.email_preferences_complete?
        static_path('email-preferences')
      else
        my_modules_path
      end
    elsif resource.private_beta_registration_complete?
      static_path('new-registration')
    else
      edit_registration_name_path
    end
  end
end

app/views/user/_debug.html.slim
- if debug?
  pre.debug_dump
    hr

    | setting_type_id: #{current_user.setting_type_id}
    br
    | setting_type: #{current_user.setting_type}
    br
    | setting_type_other: #{current_user.setting_type_other}
    br
    | role_type: #{current_user.role_type}
    br
    | role_type_other: #{current_user.role_type_other}
    br
    | local_authority: #{current_user.local_authority}
    br
    | training_emails: #{current_user.training_emails}
    br
    | early_years_emails: #{current_user.early_years_emails}

app/views/user/check_email.html.slim
.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    h1.govuk-heading-l Check your email

    p.govuk-body
      | We have sent you an email with instructions for how to verify your email address.  We sent the email to:

    p class="govuk-body govuk-!-font-weight-bold"
      = @user.email

    p.govuk-body
      | To continue setting up your training account you must click the link in the email. If you have not received the email after a few minutes, please check you spam folder.

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = govuk_details(summary_text: "Need us to resend the email?") do
      = govuk_link_to "I haven't received the email", new_confirmation_path(@user)
      br/
      = govuk_link_to "I don't have access to the email address I entered", "#"

app/views/user/check_email_confirmation.html.slim
- content_for :page_title do
  = html_title t('account_confirm_check.title')

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = govuk_back_link href: url_for(:back)

    = content_resource 'account_confirm_check.intro'

    - if @user
      = content_resource 'account_confirm_check.recipient', recipient: @user.email

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = govuk_details summary_text: t('account_confirm_check.summary') do
      = content_resource 'email_advice.not_received', link: new_confirmation_path(:user)
      = content_resource 'email_advice.no_access', link: new_registration_path(:user)
      = content_resource 'email_advice.different', link: Rails.application.credentials.contact_us

app/views/user/check_email_password_reset.html.slim
- content_for :page_title do
  = html_title t('account_reset_check.title')

= govuk_back_link href: new_user_session_path

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = content_resource 'account_reset_check.intro'

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = govuk_details summary_text: t('account_reset_check.summary') do
      = content_resource 'email_advice.not_received', link: new_password_path(:user)
      = content_resource 'email_advice.different', link: Rails.application.credentials.contact_us

app/views/user/confirm_delete_account.html.slim
.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    h1.govuk-heading-l= t('confirm_delete_account.heading')
    - t('confirm_delete_account.body').each do |paragraph|
      h1.govuk-body= paragraph

    = govuk_button_to t('confirm_delete_account.confirm'), 'delete_account', warning: true
    = govuk_link_to t('confirm_delete_account.cancel'), user_path

app/views/user/edit_email.html.slim
- content_for :page_title do
  = html_title t(:title, scope: :account_email)

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = form_for current_user, url: { action: 'update_email' } do |f|
      = f.govuk_error_summary
      = f.govuk_fieldset legend: { text: 'Change email address' } do
        = f.govuk_email_field :email, autofocus: true, autocomplete: 'email', aria: { required: true }

      - if current_user.pending_reconfirmation?
        p Currently waiting confirmation for: #{current_user.unconfirmed_email}

      .govuk-button-group
        = f.govuk_submit t('links.save')
        = govuk_link_to t('links.cancel'), user_path

app/views/user/edit_password.html.slim
- content_for :page_title do
  = html_title t(:title, scope: :account_password)

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = form_for current_user, url: { action: 'update_password' } do |f|
      = f.govuk_error_summary
      = f.govuk_fieldset legend: { text: 'Change password' } do

        p.govuk-hint= password_complexity

        = f.govuk_password_field :current_password, autofocus: true, aria: { required: true }
        = f.govuk_password_field :password, aria: { required: true }
        = f.govuk_password_field :password_confirmation, aria: { required: true }

      .govuk-button-group
        = f.govuk_submit t('links.save')
        = govuk_link_to t('links.cancel'), user_path

app/views/user/edit_training_emails.html.slim
= render 'user/debug'

.govuk-grid-row
  .govuk-grid-column-full
    = form_for current_user, url: { action: 'update_training_emails' } do |f|
      = f.govuk_error_summary

      - opt_in_out(:training_emails) do |options, legend, hint|
        = f.govuk_collection_radio_buttons :training_emails, options, :id, :name, legend: { text: legend }, hint: { text: hint }

      div class='govuk-button-group govuk-!-margin-top-4'
        = f.govuk_submit t('links.save')
        = govuk_link_to t('links.cancel'), user_path

app/views/user/learning.html.slim
h1.govuk-heading-l My learning
- if ENV['RAILS_ENV'].eql?('development')
  pre.debug_dump
    | Last page
    br
    - TrainingModule.all.each do |mod|
      | #{ModuleItem.find_by(training_module: mod.name).last_page_name}: #{mod.title}
      br

.govuk-grid-row id='started'
  .govuk-grid-column-full
    h2.govuk-heading-m In progress
    - if ENV['RAILS_ENV'].eql?('development')
      pre.debug_dump
        | Furthest page
        br
        - @started.each do |mod|
          | #{@user.last_page_for(training_module: mod)['id']}: #{mod.title}
          br

    - if @started.none?
      p You have not started any modules. To begin the training course, start an available module.
    - else
      div class='govuk-grid-row govuk-!-margin-bottom-7'
        - @started.each do |mod|
          .govuk-grid-column-one-quarter
            .govuk-card__flex-container
              .govuk-card__flex-item
                .govuk-card.govuk-card--contained.govuk-card--selectable
                  a href=url_for(@user.last_page_for(training_module: mod))
                  div class='govuk-card__hero govuk-!-margin-bottom-2'
                    img src=image_path(mod.thumbnail) width=180 alt=mod.name
                  .govuk-card__content
                    h3.govuk-heading-m
                      = mod.title

hr
.govuk-grid-row id='available'
  .govuk-grid-column-full
    h2.govuk-heading-m Available modules

    ul
      - @not_started.each do |mod|
        li= link_to mod.title, training_module_content_page_path(mod, 1)

hr
.govuk-grid-row id='upcoming'
  .govuk-grid-column-full
    h2.govuk-heading-m Upcoming modules

  - TrainingModule.all.take(3).each do |mod|
    .govuk-grid-column-one-third
      .govuk-card__flex-container
        .govuk-card__flex-item
          .govuk-card.govuk-card__height
            .govuk-card__content
              h3.govuk-heading-s= mod.title
              p.govuk-body= mod.description
            .govuk-card__actions
              = govuk_link_to 'View more information about this module', training_module_content_page_path(mod, 1)

hr
.govuk-grid-row id='completed'
  .govuk-grid-column-full
    = modules_table(@completed)

app/views/user/show.html.slim
= render 'debug'

- content_for :page_title do
  = html_title t('my_account.title')

.govuk-grid-row
  .govuk-grid-column-three-quarters-from-desktop
    h1.govuk-heading-l Manage your account
    h2.govuk-heading-m Your details
    hr.govuk-section-break.govuk-section-break--l.govuk-section-break--visible

    = govuk_summary_list do |your_details|
      - your_details.with_row do |row|
        - row.with_key { 'Name' }
        - row.with_value(text: current_user.name, classes: ['data-hj-suppress'])
        - row.with_action(text: t('links.change'), href: edit_registration_name_path, visually_hidden_text: 'name', html_attributes: { id: :edit_name_registration })
      - your_details.with_row do |row|
        - row.with_key { 'Email' }
        - row.with_value(text:current_user.email, classes: ['data-hj-suppress'])
        - row.with_action(text: t('links.change'), href: edit_email_user_path, visually_hidden_text: 'email', html_attributes: { id: :edit_email_user })
      - your_details.with_row do |row|
        - row.with_key { 'Password' }
        - row.with_value { t('my_account.password_changed', date: current_user.password_last_changed) }
        - row.with_action(text: t('links.change'), href: edit_password_user_path, visually_hidden_text: 'password', html_attributes: { id: :edit_password_user })

    = govuk_summary_list do |other_details|
      - other_details.with_row do |row|
        - row.with_key { raw t('my_account.setting_details') }
        - row.with_value { nil }
        - row.with_action(text: t('links.change'), href: edit_registration_setting_type_path, visually_hidden_text: 'setting_type', html_attributes: { id: :edit_setting_type_registration })
      - other_details.with_row do |row|
        - row.with_key { 'Setting type' }
        - row.with_value(text: current_user.setting_name, classes: ['data-hj-suppress'])
      - other_details.with_row do |row|
        - row.with_key { 'Local authority' }
        - row.with_value(text: current_user.authority_name, classes: ['data-hj-suppress'])
      - other_details.with_row do |row|
        - row.with_key { 'Role' }
        - row.with_value(text: current_user.role_name, classes: ['data-hj-suppress'])

    = govuk_summary_list do |email_preferences|
      - email_preferences.with_row do |row|
        - row.with_key { raw t('my_account.email_preferences') }
        - row.with_value { nil }
      - email_preferences.with_row do |row|
        - row.with_key { 'Email updates about this training course' }
        - row.with_value(text: current_user.training_emails.nil? || current_user.training_emails ? t('.training_emails_true') : t('.training_emails_false'), classes: ['data-hj-suppress'])
        - row.with_action(text: t('links.change'), href: edit_training_emails_user_path, visually_hidden_text: 'training_emails', html_attributes: { id: :edit_training_emails_user })

    = content_resource 'my_account.closing.information'
    = govuk_button_link_to t('my_account.closing.button'), new_user_close_account_path