config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'health', to: 'home#show'
  get 'audit', to: 'home#audit'

  get 'my-modules', to: 'learning#show' # @see User#course
  get 'about-training', to: 'training/modules#index', as: :course_overview

  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unprocessable_entity', via: :all
  get '/500', to: 'errors#internal_server_error', via: :all

  resources :settings, controller: :settings, only: %i[show create]

  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               confirmations: 'confirmations',
               passwords: 'passwords',
               registrations: 'registrations',
             },
             path_names: {
               sign_in: 'sign-in',
               sign_out: 'sign-out',
               sign_up: 'sign-up',
             }

  # @see TimeoutWarning js component
  # @note these path names are required
  devise_scope :user do
    get 'check_session_timeout', to: 'timeout#check'
    get 'extend_session', to: 'timeout#extend'
    get 'users/timeout', to: 'timeout#timeout_user'
  end

  namespace :registration do
    resource :name, only: %i[edit update]
    resource :setting_type, only: %i[edit update], path: 'setting-type'
    resource :setting_type_other, only: %i[edit update], path: 'setting-type-other'
    resource :local_authority, only: %i[edit update], path: 'local-authority'
    resource :role_type, only: %i[edit update], path: 'role-type'
    resource :role_type_other, only: %i[edit update], path: 'role-type-other'
    resource :training_emails, only: %i[edit update], path: 'training-emails'
    resource :early_years_emails, only: %i[edit update], path: 'early-years-emails'
  end

  resource :user, controller: :user, only: %i[show], path: 'my-account' do
    get 'edit-email'
    get 'edit-password'
    patch 'update-email'
    patch 'update-password'
    get 'check-email-confirmation'
    get 'check-email-password-reset'
    get 'edit-training-emails'
    patch 'update-training-emails'

    resource :close_account, only: %i[new update show], path: 'close' do
      get 'reset-password'
      get 'edit-reason'
      patch 'update-reason'
      get 'confirm'
      post 'close_account'
    end

    scope module: 'training' do
      resource :notes, path: 'learning-log', only: %i[show create update]
    end
  end

  constraints proc { Rails.application.preview? || Rails.env.test? } do
    resources :snippets, id: /[^\/]+/, only: %i[show]
  end

  scope module: 'training' do
    resources :modules, only: %i[show], as: :training_modules do
      resources :pages, only: %i[index show], path: 'content-pages'
      resources :questions, only: %i[show], path: 'questionnaires'
      resources :responses, only: %i[update]
      resources :assessments, only: %i[show new], path: 'assessment-result'
    end
  end

  post '/change', to: 'hook#change'
  post '/release', to: 'hook#release'

  resources :pages, only: %i[show], path: '/', as: :static
end

app/controllers/close_accounts_controller.rb
class CloseAccountsController < ApplicationController
  before_action :authenticate_registered_user!, except: :show

  def show; end

  def new; end

  def update
    if current_user.valid_password?(user_password_params[:current_password])
      redirect_to edit_reason_user_close_account_path
    else
      current_user.errors.add(:current_password, :confirmation_invalid, message: 'Enter a valid password')
      render :new, status: :unprocessable_entity
    end
  end

  def reset_password
    sign_out current_user
    redirect_to new_user_password_path
  end

  def close_account
    current_user.send_account_closed_notification

    # TODO: refactor this internal user mailer logic
    User.new(email: Rails.configuration.internal_mailbox).send_account_closed_internal_notification(current_user.email)

    current_user.redact!
    sign_out current_user
    redirect_to user_close_account_path
  end

  def edit_reason; end

  def update_reason
    current_user.context = :close_account

    if current_user.update(user_params)
      redirect_to confirm_user_close_account_path
    else
      current_user.errors.clear
      if user_params[:closed_reason] == 'other'
        current_user.errors.add :closed_reason_custom, :blank, message: 'Enter a reason why you want to close your account'
      else
        current_user.errors.add :closed_reason, :blank, message: 'Select a reason for closing your account'
      end
      render :edit_reason, status: :unprocessable_entity
    end
  end

  def confirm; end

private

  def user_params
    params.require(:user).permit(:closed_reason, :closed_reason_custom)
  end

  def user_password_params
    params.require(:user).permit(:current_password)
  end
end

app/views/close_accounts/confirm.html.slim
- content_for :page_title do
  = html_title t('close_account.confirm.heading')

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = govuk_back_link(href: edit_reason_user_close_account_path)

    h1.govuk-heading-l= t('close_account.confirm.heading')
    = translate_markdown(t('close_account.confirm.body'))

    .govuk-button-group
      = govuk_button_to t('close_account.confirm.confirm_button'), close_account_user_close_account_path, warning: true
      = govuk_link_to t('close_account.confirm.cancel_button'), user_path

app/views/close_accounts/edit_reason.html.slim
- content_for :page_title do
  = html_title 'Tell us why you want to close your account'

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = govuk_back_link(href: user_path)

    = form_with model: current_user, url: update_reason_user_close_account_path  do |f|
      = f.govuk_error_summary
      = f.govuk_radio_buttons_fieldset(:closed_reason,
        legend: { text: 'Tell us why you want to close your account' },
        hint: { text: 'Knowing why you want to close your account will help us improve the training for everyone.' }) do
        = f.govuk_radio_button :closed_reason, 'not useful', label: { text: 'I did not find the training useful' }, link_errors: true
        = f.govuk_radio_button :closed_reason, 'no time', label: { text: 'I did not have time to do the training' }
        = f.govuk_radio_button :closed_reason, 'no longer in early years', label: { text: 'I no longer work in early years' }
        = f.govuk_radio_button :closed_reason, 'too many emails', label: { text: 'You sent me too many emails' }
        = f.govuk_radio_button :closed_reason, 'other', label: { text: 'Another reason' } do
          = f.govuk_text_field :closed_reason_custom, label: { text: 'Tell us why you want to close your account.' }
        = f.govuk_radio_divider
        = f.govuk_radio_button :closed_reason, 'prefer not to say', label: { text: 'Prefer not to say' }
      = f.govuk_submit t('links.continue')

app/views/close_accounts/new.html.slim
- content_for :page_title do
  = html_title 'For security, enter your password.'

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = govuk_back_link(href: user_path)
  
    = form_with model: current_user, url: user_close_account_path do |f|
      = f.govuk_error_summary
      = f.govuk_fieldset legend: { text: 'Enter your password' } do
        = f.govuk_password_field :current_password,
          autofocus: true,
          aria: { required: true },
          label: { text: 'For security, enter your password.' },
          hint: { text: 'Your password' } do 
          p= govuk_details(summary_text: 'Problems with your password?') do
            p.govuk-heading-s= 'I have forgotten my password'
            = "If you have forgotten your password you can "
            = govuk_link_to 'reset it', reset_password_user_close_account_path
      = f.govuk_submit t('links.continue')

app/views/close_accounts/show.html.slim
- content_for :page_title do
  = html_title t('account_closed.title')

.govuk-grid-row
  .govuk-grid-column-two-thirds-from-desktop
    = content_resource 'account_closed.body', service_name: service_name